// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	users "github.com/wisdommatt/todo-list-api/components/users"
)

// repository is an autogenerated mock type for the repository type
type repository struct {
	mock.Mock
}

// deleteUserByID provides a mock function with given fields: ctx, userID
func (_m *repository) deleteUserByID(ctx context.Context, userID string) (*users.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *users.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getUserByEmail provides a mock function with given fields: ctx, email
func (_m *repository) getUserByEmail(ctx context.Context, email string) (*users.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *users.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getUserByID provides a mock function with given fields: ctx, userID
func (_m *repository) getUserByID(ctx context.Context, userID string) (*users.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *users.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getUsers provides a mock function with given fields: ctx, lastID, limit
func (_m *repository) getUsers(ctx context.Context, lastID string, limit int) ([]users.User, error) {
	ret := _m.Called(ctx, lastID, limit)

	var r0 []users.User
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []users.User); ok {
		r0 = rf(ctx, lastID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, lastID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// saveUser provides a mock function with given fields: ctx, user
func (_m *repository) saveUser(ctx context.Context, user users.User) (*users.User, error) {
	ret := _m.Called(ctx, user)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, users.User) *users.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
