// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tasks "github.com/wisdommatt/creativeadvtech-assessment/components/tasks"

	time "time"
)

// repository is an autogenerated mock type for the repository type
type repository struct {
	mock.Mock
}

// deleteTaskByID provides a mock function with given fields: ctx, taskID
func (_m *repository) deleteTaskByID(ctx context.Context, taskID string) (*tasks.Task, error) {
	ret := _m.Called(ctx, taskID)

	var r0 *tasks.Task
	if rf, ok := ret.Get(0).(func(context.Context, string) *tasks.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getTaskByID provides a mock function with given fields: ctx, taskID
func (_m *repository) getTaskByID(ctx context.Context, taskID string) (*tasks.Task, error) {
	ret := _m.Called(ctx, taskID)

	var r0 *tasks.Task
	if rf, ok := ret.Get(0).(func(context.Context, string) *tasks.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getTaskWithTimeRange provides a mock function with given fields: ctx, userID, startTime, endTime
func (_m *repository) getTaskWithTimeRange(ctx context.Context, userID string, startTime time.Time, endTime time.Time) (*tasks.Task, error) {
	ret := _m.Called(ctx, userID, startTime, endTime)

	var r0 *tasks.Task
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) *tasks.Task); ok {
		r0 = rf(ctx, userID, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getTasks provides a mock function with given fields: ctx, userID, lastID, limit
func (_m *repository) getTasks(ctx context.Context, userID string, lastID string, limit int) ([]tasks.Task, error) {
	ret := _m.Called(ctx, userID, lastID, limit)

	var r0 []tasks.Task
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []tasks.Task); ok {
		r0 = rf(ctx, userID, lastID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, userID, lastID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// saveTask provides a mock function with given fields: ctx, task
func (_m *repository) saveTask(ctx context.Context, task tasks.Task) (*tasks.Task, error) {
	ret := _m.Called(ctx, task)

	var r0 *tasks.Task
	if rf, ok := ret.Get(0).(func(context.Context, tasks.Task) *tasks.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, tasks.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
