name: AWS Setup / Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup env file
      run: |
        echo `ECR_URI="${{ secrets.ECR_URI }}"
        ECR_REGION="${{ secrets.ECR_REGION }}"
        ECR_USERNAME="${{ secrets.ECR_USERNAME }}"
        ECR_PASSWORD="${{ secrets.ECR_PASSWORD }}"
        AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        MONGODB_URI="${{ secrets.MONGODB_URI }}"` > .env

    - name: Deploy Docker Image
      run: |
        ./build/scripts/image-deploy.sh
