name: AWS Setup / Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_ECR_URI: ${{ secrets.ECR_URI }}
        envkey_ECR_REGION: ${{ secrets.ECR_REGION }}
        envkey_ECR_USERNAME: ${{ secrets.ECR_USERNAME }}
        envkey_ECR_PASSWORD: ${{ secrets.ECR_PASSWORD }}
        envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
        file_name: .env
        fail_on_empty: true

    - name: Deploy Docker Image
      run: |
        cat .env
        dotenv --version
        ./build/scripts/image-deploy.sh
